global:
  scrape_interval: 1s # TODO configure

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
